//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationProject.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string DATERANGE_TYPENAME_MONTH {
            get {
                return ResourceManager.GetString("DATERANGE_TYPENAME_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string DATERANGE_TYPENAME_YEAR {
            get {
                return ResourceManager.GetString("DATERANGE_TYPENAME_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account:.
        /// </summary>
        internal static string PAGE_ADDEXPENSE_BANKACCOUNTFIELD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSE_BANKACCOUNTFIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string PAGE_ADDEXPENSE_BUTTONADD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSE_BUTTONADD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string PAGE_ADDEXPENSE_BUTTONEXIT_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSE_BUTTONEXIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency amount:.
        /// </summary>
        internal static string PAGE_ADDEXPENSE_CURRENCYAMOUNTFIELD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSE_CURRENCYAMOUNTFIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses category:.
        /// </summary>
        internal static string PAGE_ADDEXPENSE_EXPENSECATEGORYFIELD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSE_EXPENSECATEGORYFIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        internal static string PAGE_ADDEXPENSE_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense name:.
        /// </summary>
        internal static string PAGE_ADDEXPENSE_NAMEFIELD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSE_NAMEFIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string PAGE_ADDEXPENSECATEGORY_BUTTONADD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSECATEGORY_BUTTONADD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string PAGE_ADDEXPENSECATEGORY_BUTTONEXIT_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSECATEGORY_BUTTONEXIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image:.
        /// </summary>
        internal static string PAGE_ADDEXPENSECATEGORY_CATEGORYIMAGEPATH_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSECATEGORY_CATEGORYIMAGEPATH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency amount:.
        /// </summary>
        internal static string PAGE_ADDEXPENSECATEGORY_CURRENCYAMOUNTFIELD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSECATEGORY_CURRENCYAMOUNTFIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image....
        /// </summary>
        internal static string PAGE_ADDEXPENSECATEGORY_IMAGESELECTOR_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSECATEGORY_IMAGESELECTOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense category.
        /// </summary>
        internal static string PAGE_ADDEXPENSECATEGORY_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSECATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name:.
        /// </summary>
        internal static string PAGE_ADDEXPENSECATEGORY_NAMEFIELD_NAME {
            get {
                return ResourceManager.GetString("PAGE_ADDEXPENSECATEGORY_NAMEFIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string PAGE_ANALYSIS_BUTTON_ANALYSIS {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_BUTTON_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string PAGE_ANALYSIS_BUTTON_PLAN {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_BUTTON_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string PAGE_ANALYSIS_NAME {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_EXPENSES_BUTTON_ADD {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_EXPENSES_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expenses category.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_EXPENSES_BUTTON_ADDCATEGORY {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_EXPENSES_BUTTON_ADDCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_EXPENSES_NAME {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_EXPENSES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_EXPENSES_TABLE_HEADER_NAME {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_EXPENSES_TABLE_HEADER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_EXPENSES_TABLE_HEADER_VALUE {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_EXPENSES_TABLE_HEADER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add income.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_INCOME_BUTTON_ADD {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_INCOME_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_INCOME_NAME {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_INCOME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_INCOME_TABLE_HEADER_NAME {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_INCOME_TABLE_HEADER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string PAGE_ANALYSIS_TAB_INCOME_TABLE_HEADER_VALUE {
            get {
                return ResourceManager.GetString("PAGE_ANALYSIS_TAB_INCOME_TABLE_HEADER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts:.
        /// </summary>
        internal static string PAGE_INTER_BANKACCOUNTS_NAME {
            get {
                return ResourceManager.GetString("PAGE_INTER_BANKACCOUNTS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string PAGE_PLAN_NAME {
            get {
                return ResourceManager.GetString("PAGE_PLAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expenses category.
        /// </summary>
        internal static string PAGE_PLAN_TAB_EXPENSES_BUTTON_ADDCATEGORY {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_EXPENSES_BUTTON_ADDCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string PAGE_PLAN_TAB_EXPENSES_NAME {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_EXPENSES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PAGE_PLAN_TAB_EXPENSES_TABLE_HEADER_NAME {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_EXPENSES_TABLE_HEADER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned amount.
        /// </summary>
        internal static string PAGE_PLAN_TAB_EXPENSES_TABLE_HEADER_PLANNEDVALUE {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_EXPENSES_TABLE_HEADER_PLANNEDVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual amount.
        /// </summary>
        internal static string PAGE_PLAN_TAB_EXPENSES_TABLE_HEADER_REALVALUE {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_EXPENSES_TABLE_HEADER_REALVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string PAGE_PLAN_TAB_INCOME_NAME {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_INCOME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PAGE_PLAN_TAB_INCOME_TABLE_HEADER_NAME {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_INCOME_TABLE_HEADER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned amount.
        /// </summary>
        internal static string PAGE_PLAN_TAB_INCOME_TABLE_HEADER_PLANNEDVALUE {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_INCOME_TABLE_HEADER_PLANNEDVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual amount.
        /// </summary>
        internal static string PAGE_PLAN_TAB_INCOME_TABLE_HEADER_REALVALUE {
            get {
                return ResourceManager.GetString("PAGE_PLAN_TAB_INCOME_TABLE_HEADER_REALVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same value is already in use..
        /// </summary>
        internal static string VALUE_INPUT_ERROR_DUPLICATE_VALUE {
            get {
                return ResourceManager.GetString("VALUE_INPUT_ERROR_DUPLICATE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input box is empty..
        /// </summary>
        internal static string VALUE_INPUT_ERROR_EMPTY_VALUE {
            get {
                return ResourceManager.GetString("VALUE_INPUT_ERROR_EMPTY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value contains invalid symbol(s): .
        /// </summary>
        internal static string VALUE_INPUT_ERROR_INVALID_SYMBOL {
            get {
                return ResourceManager.GetString("VALUE_INPUT_ERROR_INVALID_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is outside of expected bounds: .
        /// </summary>
        internal static string VALUE_INPUT_ERROR_OUT_OF_BOUNDS {
            get {
                return ResourceManager.GetString("VALUE_INPUT_ERROR_OUT_OF_BOUNDS", resourceCulture);
            }
        }
    }
}
